# Simple pipeline to copy specific files to Azure Web App

name: Deploy Web App (NET)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    #needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4713EC8B5253400EA70A8B1871E40C71 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BF82199CE4DD4C3AA60EE8FBBD8161AC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F7469B9B335F4E40AEB0CCA225B1DC83 }}

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
        
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myWebAppUsing-NET-GitHub'
          slot-name: 'Production'
          package: .
